import type { Candidate, Job, PipelineDistributionPoint, TalentMetricPoint } from './types';

export const talentJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Analista de DP Sênior',
    status: 'aberta',
    department: 'Departamento Pessoal',
    seniority: 'Sênior',
    applicants: 32,
    openDays: 12,
    location: 'São Paulo · Híbrido',
    salaryRange: 'R$ 7.500 — R$ 9.200',
    requirements: ['eSocial', 'LGPD', 'Automação de rotinas', 'Power BI'],
    summary: 'Liderar rotinas críticas de folha, admissão e integrações com foco em eficiência operacional.',
  },
  {
    id: 'job-2',
    title: 'Tech Recruiter',
    status: 'aberta',
    department: 'Talent Acquisition',
    seniority: 'Pleno',
    applicants: 21,
    openDays: 7,
    location: 'Remoto · Brasil',
    salaryRange: 'R$ 5.800 — R$ 7.000',
    requirements: ['ATS', 'Employer Branding', 'Entrevista por competências'],
    summary: 'Conduzir hunting, pipeline e coordenação de entrevistas para posições de produto e engenharia.',
  },
  {
    id: 'job-3',
    title: 'Especialista LGPD RH',
    status: 'pausada',
    department: 'Compliance',
    seniority: 'Sênior',
    applicants: 14,
    openDays: 19,
    location: 'Curitiba · Presencial',
    salaryRange: 'R$ 8.000 — R$ 10.500',
    requirements: ['LGPD', 'Auditoria', 'Jurídico Trabalhista'],
    summary: 'Estruturar políticas, base legal e governança de dados pessoais sensíveis no RH.',
  },
  {
    id: 'job-4',
    title: 'HRBP de Operações',
    status: 'fechada',
    department: 'People',
    seniority: 'Pleno',
    applicants: 18,
    openDays: 25,
    location: 'Belo Horizonte · Híbrido',
    salaryRange: 'R$ 6.500 — R$ 8.000',
    requirements: ['Indicadores', 'Clima', 'Gestão de líderes'],
    summary: 'Atuar ao lado da operação com foco em performance, retenção e desenho organizacional.',
  },
];

export const talentCandidates: Candidate[] = [
  {
    id: 'cand-1',
    name: 'Mariana Costa',
    email: 'mariana.costa@talenthub.dev',
    phone: '(11) 98877-1234',
    age: 31,
    origin: 'linkedin',
    stage: 'entrevista',
    risk: 'baixo',
    role: 'Analista de DP Sênior',
    score: { total: 91, technical: 94, behavioral: 88, risk: 16, aderencia: 93 },
    city: 'São Paulo',
    state: 'SP',
    summary: 'Especialista em rotinas de folha com forte experiência em compliance, automação e liderança de squads operacionais.',
    skills: ['eSocial', 'Power BI', 'LGPD', 'Gestão de Processos'],
    aiInsights: [
      { title: 'Fit técnico elevado', text: 'Excelente aderência para DP sênior com histórico consistente em empresas reguladas.' },
      { title: 'Risco baixo', text: 'Sem inconsistências relevantes nas fontes consultadas e documentação quase completa.' },
    ],
    location: { city: 'São Paulo', state: 'SP', x: 72, y: 62 },
    documents: [
      { id: 'doc-1', type: 'Currículo', title: 'CV atualizado.pdf', updatedAt: 'Hoje · 09:12', status: 'validado' },
      { id: 'doc-2', type: 'Certificado', title: 'Certificação eSocial.pdf', updatedAt: 'Ontem · 17:40', status: 'validado' },
      { id: 'doc-3', type: 'Portfólio', title: 'Cases de automação.pptx', updatedAt: 'Ontem · 10:15', status: 'pendente' },
    ],
    timeline: [
      { id: 't1', title: 'Aplicação recebida', description: 'Cadastro originado via LinkedIn com currículo anexado.', date: '12 Mar · 09:14' },
      { id: 't2', title: 'Triagem IA concluída', description: 'Score inicial de 89 com destaque em compliance.', date: '12 Mar · 09:17' },
      { id: 't3', title: 'Entrevista agendada', description: 'Conversa com liderança de People Ops confirmada.', date: '14 Mar · 16:30' },
    ],
    enrichments: [
      { source: 'Receita Federal', status: 'concluído', updatedAt: 'Hoje · 08:52', data: { situação: 'Regular', nome_empresarial: 'N/A', score_risco: 12 } },
      { source: 'CNJ', status: 'concluído', updatedAt: 'Hoje · 08:55', data: { ocorrências: 0, observação: 'Sem registros relevantes' } },
      { source: 'TST', status: 'processando', updatedAt: 'Hoje · 08:57', data: { status: 'Processando fila', prioridade: 'Alta' } },
    ],
    linkedJobIds: ['job-1'],
  },
  {
    id: 'cand-2',
    name: 'Rafael Almeida',
    email: 'rafael.almeida@talenthub.dev',
    phone: '(21) 97766-2211',
    age: 28,
    origin: 'site',
    stage: 'triagem',
    risk: 'médio',
    role: 'Tech Recruiter',
    score: { total: 84, technical: 81, behavioral: 90, risk: 39, aderencia: 86 },
    city: 'Rio de Janeiro',
    state: 'RJ',
    summary: 'Recrutador com experiência em hunting para tecnologia e construção de comunidades de talento.',
    skills: ['Hunting', 'Employer Branding', 'People Analytics'],
    aiInsights: [
      { title: 'Comunicação forte', text: 'Feedbacks destacam condução madura de entrevistas e construção de rapport.' },
      { title: 'Revisar risco', text: 'Pendência documental em histórico profissional ainda exige validação adicional.' },
    ],
    location: { city: 'Rio de Janeiro', state: 'RJ', x: 76, y: 68 },
    documents: [
      { id: 'doc-4', type: 'Currículo', title: 'Rafael_Resume.pdf', updatedAt: 'Hoje · 07:20', status: 'validado' },
      { id: 'doc-5', type: 'Laudo', title: 'Validação cadastral.pdf', updatedAt: 'Hoje · 07:40', status: 'vencendo' },
    ],
    timeline: [
      { id: 't4', title: 'Cadastro iniciado', description: 'Lead vindo da página pública de carreira.', date: '11 Mar · 11:05' },
      { id: 't5', title: 'Busca inteligente', description: 'IA sugeriu match para Tech Recruiter com 86% de aderência.', date: '11 Mar · 11:12' },
      { id: 't6', title: 'Triagem manual', description: 'Equipe pediu aprofundamento em métricas de funil.', date: '13 Mar · 15:08' },
    ],
    enrichments: [
      { source: 'Receita Federal', status: 'concluído', updatedAt: 'Hoje · 07:55', data: { situação: 'Regular', score_risco: 31 } },
      { source: 'APIs públicas', status: 'concluído', updatedAt: 'Hoje · 08:03', data: { linkedin_validado: true, senioridade: 'Pleno' } },
    ],
    linkedJobIds: ['job-2'],
  },
  {
    id: 'cand-3',
    name: 'Juliana Nunes',
    email: 'juliana.nunes@talenthub.dev',
    phone: '(41) 99123-4312',
    age: 35,
    origin: 'importação',
    stage: 'proposta',
    risk: 'baixo',
    role: 'Especialista LGPD RH',
    score: { total: 93, technical: 96, behavioral: 85, risk: 11, aderencia: 95 },
    city: 'Curitiba',
    state: 'PR',
    summary: 'Executiva de privacidade com foco em RH, governança e desenho de controles em ambientes regulados.',
    skills: ['LGPD', 'Auditoria', 'Governança de dados', 'Políticas internas'],
    aiInsights: [
      { title: 'Perfil premium', text: 'Aderência excepcional para compliance e governança em operações de RH.' },
      { title: 'Pronta para oferta', text: 'Gap principal está apenas em alinhamento de expectativa salarial.' },
    ],
    location: { city: 'Curitiba', state: 'PR', x: 65, y: 78 },
    documents: [
      { id: 'doc-6', type: 'Currículo', title: 'Juliana_Nunes.pdf', updatedAt: 'Ontem · 18:02', status: 'validado' },
      { id: 'doc-7', type: 'Certificado', title: 'DPO Certification.pdf', updatedAt: 'Ontem · 18:10', status: 'validado' },
    ],
    timeline: [
      { id: 't7', title: 'Importação do pool', description: 'Perfil importado de base histórica com score alto.', date: '09 Mar · 10:20' },
      { id: 't8', title: 'Due diligence', description: 'Consultas concluídas sem achados críticos.', date: '10 Mar · 14:50' },
      { id: 't9', title: 'Proposta em elaboração', description: 'Aguardando aprovação final da diretoria.', date: '15 Mar · 09:05' },
    ],
    enrichments: [
      { source: 'Receita Federal', status: 'concluído', updatedAt: 'Ontem · 16:40', data: { situação: 'Regular', score_risco: 9 } },
      { source: 'CNJ', status: 'concluído', updatedAt: 'Ontem · 16:44', data: { ocorrências: 0, score_risco: 4 } },
      { source: 'TST', status: 'concluído', updatedAt: 'Ontem · 16:50', data: { processos: 0, observação: 'Nenhuma ocorrência' } },
    ],
    linkedJobIds: ['job-3'],
  },
  {
    id: 'cand-4',
    name: 'Diego Santos',
    email: 'diego.santos@talenthub.dev',
    phone: '(31) 98755-6789',
    age: 29,
    origin: 'indicação',
    stage: 'novo',
    risk: 'baixo',
    role: 'HRBP de Operações',
    score: { total: 79, technical: 74, behavioral: 88, risk: 18, aderencia: 80 },
    city: 'Belo Horizonte',
    state: 'MG',
    summary: 'HRBP com bom repertório de gestão de líderes e desenho de rotinas operacionais.',
    skills: ['Business Partner', 'Clima', 'KPIs', 'Treinamento'],
    aiInsights: [
      { title: 'Bom potencial', text: 'Perfil generalista forte para contextos de operação com times distribuídos.' },
      { title: 'Requer aprofundamento', text: 'Necessário validar profundidade em indicadores de turnover e absenteísmo.' },
    ],
    location: { city: 'Belo Horizonte', state: 'MG', x: 70, y: 70 },
    documents: [
      { id: 'doc-8', type: 'Currículo', title: 'DiegoSantos.pdf', updatedAt: 'Hoje · 06:40', status: 'pendente' },
    ],
    timeline: [
      { id: 't10', title: 'Indicação interna', description: 'Líder regional sugeriu inclusão prioritária no banco.', date: '15 Mar · 08:15' },
    ],
    enrichments: [
      { source: 'APIs públicas', status: 'processando', updatedAt: 'Hoje · 09:05', data: { status: 'Fila iniciada', prioridade: 'Normal' } },
    ],
    linkedJobIds: ['job-4'],
  },
  {
    id: 'cand-5',
    name: 'Larissa Ferreira',
    email: 'larissa.ferreira@talenthub.dev',
    phone: '(51) 99888-2233',
    age: 33,
    origin: 'linkedin',
    stage: 'contratado',
    risk: 'baixo',
    role: 'Tech Recruiter',
    score: { total: 95, technical: 92, behavioral: 97, risk: 8, aderencia: 96 },
    city: 'Porto Alegre',
    state: 'RS',
    summary: 'Referência em recrutamento tech com histórico de redução de time-to-hire e forte atuação analítica.',
    skills: ['Tech Hiring', 'Hiring Manager Enablement', 'Analytics'],
    aiInsights: [
      { title: 'Caso de sucesso', text: 'Contratação acelerada com aderência cultural e técnica acima da média.' },
      { title: 'Benchmark', text: 'Pode ser utilizada como perfil referência para novas buscas.' },
    ],
    location: { city: 'Porto Alegre', state: 'RS', x: 60, y: 86 },
    documents: [
      { id: 'doc-9', type: 'Currículo', title: 'Larissa_resume.pdf', updatedAt: '10 Mar · 12:20', status: 'validado' },
    ],
    timeline: [
      { id: 't11', title: 'Oferta aceita', description: 'Candidata aceitou proposta e iniciou onboarding.', date: '10 Mar · 18:44' },
    ],
    enrichments: [
      { source: 'Receita Federal', status: 'concluído', updatedAt: '09 Mar · 08:30', data: { situação: 'Regular', score_risco: 6 } },
    ],
    linkedJobIds: ['job-2'],
  },
  {
    id: 'cand-6',
    name: 'Thiago Ribeiro',
    email: 'thiago.ribeiro@talenthub.dev',
    phone: '(85) 99777-7766',
    age: 27,
    origin: 'site',
    stage: 'triagem',
    risk: 'alto',
    role: 'Analista de DP Sênior',
    score: { total: 68, technical: 72, behavioral: 63, risk: 71, aderencia: 69 },
    city: 'Fortaleza',
    state: 'CE',
    summary: 'Perfil promissor tecnicamente, porém com sinais de inconsistência cadastral e aderência parcial ao escopo.',
    skills: ['Folha', 'Admissão', 'Controle documental'],
    aiInsights: [
      { title: 'Atenção jurídica', text: 'Achados em fontes públicas elevam a necessidade de revisão antes do avanço.' },
      { title: 'Plano de ação', text: 'Solicitar documentação complementar e validação do histórico profissional.' },
    ],
    location: { city: 'Fortaleza', state: 'CE', x: 84, y: 52 },
    documents: [
      { id: 'doc-10', type: 'Currículo', title: 'Thiago_Ribeiro.pdf', updatedAt: 'Hoje · 05:12', status: 'validado' },
      { id: 'doc-11', type: 'Laudo', title: 'Background check.pdf', updatedAt: 'Hoje · 05:45', status: 'vencendo' },
    ],
    timeline: [
      { id: 't12', title: 'Consulta ampliada', description: 'Fila de enriquecimento manualmente escalada.', date: '15 Mar · 10:02' },
    ],
    enrichments: [
      { source: 'CNJ', status: 'concluído', updatedAt: 'Hoje · 06:01', data: { ocorrências: 2, score_risco: 64 } },
      { source: 'TST', status: 'concluído', updatedAt: 'Hoje · 06:11', data: { processos: 1, score_risco: 57 } },
    ],
    linkedJobIds: ['job-1'],
  },
];

export const talentTrend: TalentMetricPoint[] = [
  { label: 'Jan', candidatos: 18, score: 74 },
  { label: 'Fev', candidatos: 24, score: 78 },
  { label: 'Mar', candidatos: 29, score: 81 },
  { label: 'Abr', candidatos: 34, score: 83 },
  { label: 'Mai', candidatos: 31, score: 84 },
  { label: 'Jun', candidatos: 38, score: 86 },
];

export const talentPipelineDistribution: PipelineDistributionPoint[] = [
  { stage: 'novo', total: 14 },
  { stage: 'triagem', total: 22 },
  { stage: 'entrevista', total: 11 },
  { stage: 'proposta', total: 6 },
  { stage: 'contratado', total: 4 },
];

export const talentAiSignals = [
  {
    title: 'Candidatos prontos para proposta',
    value: '6 perfis',
    description: 'IA detectou candidatos com aderência acima de 90 e risco controlado nas últimas 48h.',
  },
  {
    title: 'Risco concentrado',
    value: '2 alertas',
    description: 'Triagem jurídica indica necessidade de validação reforçada em duas candidaturas da etapa de triagem.',
  },
  {
    title: 'Melhor origem do mês',
    value: 'LinkedIn',
    description: 'Origem entrega maior score médio e menor tempo até entrevista para vagas analíticas.',
  },
];
