
-- Executive alerts generated by the predictive AlertEngine
CREATE TABLE public.governance_executive_alerts (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES public.tenants(id),
  employee_id TEXT NOT NULL,
  alert_type TEXT NOT NULL, -- 'escalation_risk' | 'termination_risk' | 'legal_exposure' | 'pattern_detected'
  severity TEXT NOT NULL DEFAULT 'high', -- 'medium' | 'high' | 'critical'
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  trigger_factors JSONB NOT NULL DEFAULT '[]',
  risk_score NUMERIC NOT NULL DEFAULT 0,
  recommended_actions JSONB NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'open', -- 'open' | 'acknowledged' | 'resolved' | 'dismissed'
  acknowledged_by TEXT,
  acknowledged_at TIMESTAMPTZ,
  resolved_by TEXT,
  resolved_at TIMESTAMPTZ,
  resolution_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.governance_executive_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant isolation for governance_executive_alerts"
  ON public.governance_executive_alerts FOR ALL
  USING (tenant_id IN (SELECT t.id FROM tenants t WHERE t.id = tenant_id));

CREATE INDEX idx_gov_alerts_tenant_status
  ON public.governance_executive_alerts(tenant_id, status, created_at DESC);

CREATE INDEX idx_gov_alerts_employee
  ON public.governance_executive_alerts(tenant_id, employee_id, created_at DESC);

-- Tenant-configurable alert thresholds
CREATE TABLE public.governance_alert_configs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES public.tenants(id),
  rule_code TEXT NOT NULL,
  rule_name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  conditions JSONB NOT NULL DEFAULT '{}',
  severity TEXT NOT NULL DEFAULT 'high',
  notify_channels JSONB NOT NULL DEFAULT '["in_app"]',
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(tenant_id, rule_code)
);

ALTER TABLE public.governance_alert_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant isolation for governance_alert_configs"
  ON public.governance_alert_configs FOR ALL
  USING (tenant_id IN (SELECT t.id FROM tenants t WHERE t.id = tenant_id));

CREATE TRIGGER update_governance_executive_alerts_updated_at
  BEFORE UPDATE ON public.governance_executive_alerts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_governance_alert_configs_updated_at
  BEFORE UPDATE ON public.governance_alert_configs
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
